name: CNNSpectrogram
params:
  base_filters: 8
  kernel_sizes:
    - 16
    - ${downsample_rate}
  stride: ${downsample_rate}
  sigmoid: true
  reinit: true
  required_height: 32
  skip_connections_features: []