data_dir: /mnt/s4610340-sleep_states/data/raw
processed_dir: /mnt/s4610340-sleep_states/data/processed
output_dir: /mnt/s4610340-sleep_states/kaggle-detect_sleep_states/outputs
model_dir: /mnt/s4610340-sleep_states/kaggle-detect_sleep_states/models
sub_dir: ./
mlflow_store_dir: /mnt/s4610340-sleep_states/ml-runs