data_dir: /home/egor/Projects/Pycharm/kaggle-detect_sleep_states/data/raw
processed_dir: /home/egor/Projects/Pycharm/kaggle-detect_sleep_states/data/processed
output_dir: /home/egor/Projects/Pycharm/kaggle-detect_sleep_states/logs
model_dir: /home/egor/Projects/Pycharm/kaggle-detect_sleep_states/models
sub_dir: ./