# ---------- Overriding hydra default configs ----------
hydra:
  launcher:
    n_jobs: 4

  job:
    name: train
    chdir: true
  run:
    dir: ${dir.output_dir}/${hydra.job.name}/${exp_name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${dir.output_dir}/${hydra.job.name}/${exp_name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: run${hydra.job.num}

defaults:
  - _self_
  - dir: alpha
  - dataset: seg
  - model: Spec2DCNN
  - feature_extractor: CNNSpectrogram
  - decoder: UNet1DDecoder
  - split: fold_0
  - loss: BCE
  - override hydra/launcher: joblib

seed: 42
exp_name: dummy
run_name: dummy
batch_size: 32
num_workers: 6
duration: 5760
downsample_rate: 2
upsample_rate: 1
n_chunks_visualize: 5

trainer:
  epochs: 50
  accelerator: auto
  use_amp: true
  debug: false
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  monitor: val_loss
  monitor_mode: min
  check_val_every_n_epoch: 1
  gpus: 1

aug:
  mixup_prob: 0.0
  mixup_alpha: 0.4
  cutmix_prob: 0.0
  cutmix_alpha: 0.4
  
# post_process
pp:
  score_th: 0.05
  distance: 10

# label
labels:
  - "asleep"
  - "event_onset"
  - "event_wakeup"

target_labels_idx:
  - 1
  - 2

# feature
features:
  - "anglez"
  - "enmo"
  # - "step"
  # - "month_sin"
  # - "month_cos"
  # - "day_of_week_sin"
  # - "day_of_week_cos"
  - "hour_sin"
  - "hour_cos"
  # - "minute_sin"
  # - "minute_cos"
  # - "anglez_sin"
  # - "anglez_cos"
  # - "anglez_total_variation"
  # - "enmo_total_variation"

# optimizer
optimizer:
  lr: 0.0005

# scheduler
scheduler:
  num_warmup_steps: 0
